version: 0.2

env:
  variables:
    DATABASE_URL: "sqlite:///:memory:"
    TESTING: "True"

phases:
  install:
    runtime-versions:
      python: 3.11
    commands:
      - echo "Instalando dependencias del proyecto..."
      - python --version
      - python -m pip install --upgrade pip
      - pip install -r requirements.txt
      - pip install pytest pytest-flask

  pre_build:
    commands:
      - echo "Preparando ambiente de pruebas..."
      - export PYTHONPATH=$PYTHONPATH:$(pwd)
      - echo "DATABASE_URL=$DATABASE_URL"
      - echo "TESTING=$TESTING"
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin 879980497605.dkr.ecr.us-east-2.amazonaws.com


  build:
    commands:
      - echo "Ejecutando pruebas unitarias..."
      - pytest tests.py -v
      - echo "Pruebas finalizadas correctamente."
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t repo-blacklist .
      - docker tag repo-blacklist:latest 879980497605.dkr.ecr.us-east-2.amazonaws.com/repo-blacklist:latest

  post_build:
    commands:
      - echo "Build finalizado."
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push 879980497605.dkr.ecr.us-east-2.amazonaws.com/repo-blacklist:latest
      - echo Writing Image Definitions file...
      - printf '[{"name":"repo-blacklist","imageUri":"879980497605.dkr.ecr.us-east-2.amazonaws.com/repo-blacklist:latest"}]' > imagedefinitions.json
      - printf '{"ImageURI":"879980497605.dkr.ecr.us-east-2.amazonaws.com/repo-blacklist:latest"}' > imageDetail.json
      - cat imagedefinitions.json 

artifacts:
  files:
    - taskdef.json
    - appspec.json
    - imageDetail.json
  discard-paths: yes